title: "NER in kbase"
description: "Named entity recognition for documents in kbase using spacy."
vars:
  name: "ner_kbase"
  lang: "en"
  version: "0.0.0"
  pipeline: "en_core_web_md"
  train: "20210320-glue-dir-kbase-dev-sagemaker-ground-truth/train.spacy"
  dev: "20210320-glue-dir-kbase-dev-sagemaker-ground-truth/dev.spacy"
  test: "20210320-glue-dir-kbase-dev-sagemaker-ground-truth/test.spacy"
  # Set your GPU ID, -1 is CPU
  gpu_id: -1

directories: ["assets", "corpus", "configs", "training", "scripts", "packages"]

assets:
  - dest: "assets/${vars.train}"
    description: "Annotated training data, preprocessed and stored in spacy's binary format."
  - dest: "assets/${vars.dev}"
    description: "Annotated development data, preprocessed and stored in spacy's binary format."
  - dest: "assets/${vars.test}"
    description: "Annotated test data, preprocessed and stored in spacy's binary format."

workflows:
  all:
    - download
    - convert

commands:
  - name: "download"
    help: "Download the pretrained pipeline"
    script:
      - "python -m spacy download ${vars.pipeline}"

  - name: "convert"
    help: "Convert the data to spaCy's binary format, removing all non-NER annotation."
    script:
      - "python scripts/convert.py ${vars.lang} assets/${vars.train} corpus/train.spacy"
      - "python scripts/convert.py ${vars.lang} assets/${vars.dev} corpus/dev.spacy"
      - "python scripts/convert.py ${vars.lang} assets/${vars.test} corpus/test.spacy"
    deps:
      - "assets/${vars.train}"
      - "assets/${vars.dev}"
      - "assets/${vars.test}"
      - "scripts/convert.py"
    outputs:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
      - "corpus/test.spacy"
